---
title: Squares Conference
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  speakers:
    title: Speakers
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    SEO:
      Title:
      Description:
      Keywords:
    Body Class:
    Hero Text:
    Hero Image:
- scope:
    path: ''
    type: speakers
  values:
    Job Title: 
    Featured Image: 
    Red Image: 
    Twitter URL: 
    Website URL: 
    Options:
      Is Featured: 
      Is Large: 
    Topic Title: 
    Topic Description: 
Company Name: |
  Circles Company
Website Name: |
  Squares Conference
email: your-email@domain.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
