---
title: Squares Conference
timezone: America/New_York
collections:
  panelists:
    title: Panelists
    output: false
  panels:
    title: Panels
    output: false
  parties:
    title: Parties
    output: false
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  schedule:
    title: Schedule
    output: false
  sessions:
    title: Sessions
    output: false
  speakers:
    title: Speakers
    output: false
  sponsors:
    title: Sponsors
    output: false
  team:
    title: Team
    output: false
  uploads:
    title: Uploads
    output: true
  workshops:
    title: Workshops
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    SEO:
      Title: 
      Desc: 
      Keywords: 
    Body Class: 
    Hero Text: 
    Hero Image: 
    Is In Menu: 
- scope:
    path: ''
    type: speakers
  values:
    Job Title: 
    Featured Image: 
    Red Image: 
    Twitter URL: 
    Website URL: 
    Topic Title: 
    Topic Description: 
- scope:
    path: ''
    type: sponsors
  values:
    Type: |
      Premier, Standard or Partner
    Image: 
    URL: 
    Tagline: 
- scope:
    path: ''
    type: workshops
  values:
    Category: Design, UX, Front-End, Development, or Product
    Track: 1 or 2
    Date: 
    Time: ie. 1.5 hrs
    Teacher:
      Name: 
      Job Title: 
      Featured Image: 
      Red Image: 
      Twitter URL: 
      Website URL: 
- scope:
    path: ''
    type: parties
  values:
    Address Text: 
    Date: 
- scope:
    path: ''
    type: team
  values:
    Job Title: 
    Featured Image: 
    Red Image: 
    Twitter URL: 
    Website URL: 
- scope:
    path: ''
    type: schedule
  values:
    Date: 
    Image: 
    Type: Workshop, Panel, Party, or Session
    Info:
      Workshops:
      - ''
      Panels: 
      Parties: 
      Sessions: 
- scope:
    path: ''
    type: panelists
  values:
    Job Title: 
    Featured Image: 
    Red Image: 
    Twitter URL: 
    Website URL: 
    Panel: 
- scope:
    path: ''
    type: panels
  values:
    Date: 
    Image: 
Company Name: |
  Circles Company
Website Name: |
  Squares Conference
email: your-email@domain.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 
url: http://squaresconference2017.siteleaf.net
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
